#file: noinspection SpellCheckingInspection
name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Create GPG Key ring
        shell: bash
        run: |
          gpg --batch --pinentry-mode loopback --passphrase $passphrase --export-secret-keys -o ./secring.gpg
          gpg --batch --pinentry-mode loopback --passphrase $passphrase --export-secret-keys -o ./ksp-annotations/secring.gpg
        env:
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Make gradlew executable
        if: matrix.platform != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        shell: bash
        run: |
          ./gradlew publish -Pgradle.publish.key=$gradle_publish_key -Pgradle.publish.secret=$gradle_publish_secret -Psigning.keyId=$signing_keyId -Psigning.password=$signing_password -Psigning.secretKeyRingFile=./secring.gpg
        env:
          repoPassword: ${{ secrets.OSSRH_PASSWORD }}
          repoUsername: ${{ vars.OSSRH_USERNAME }}
          gradle_publish_key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle_publish_secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          signing_keyId: ${{ secrets.SIGNING_KEY_ID }}
          signing_password: ${{ secrets.SIGNING_PASSWORD }}
      - name: Publish to Publisher Portal
        shell: bash
        run: |
          curl -X POST \
            -u "$username:$password" \
            --no-buffer \
            --no-keepalive \
            --max-time 0 \
            "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.github.devngho"
        env:
          username: ${{ vars.OSSRH_USERNAME }}
          password: ${{ secrets.OSSRH_PASSWORD }}