#file: noinspection SpellCheckingInspection
name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  create_staging_repository:
    name: Create staging repository
    runs-on: ubuntu-latest
    outputs:
      repository_id: ${{ steps.mask.outputs.repository_id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@main
        with:
          username: ${{ vars.OSSRH_USERNAME }}
          password: ${{ secrets.OSSRH_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
          base_url: https://s01.oss.sonatype.org/service/local/
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}
      - name: Mask values
        id: mask
        shell: bash
        run: |
          TOKEN_BASE64=`echo -n ${{ steps.create.outputs.repository_id }} | base64 -w 0`
          echo -n "repository_id=$TOKEN_BASE64" >> $GITHUB_OUTPUT
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    needs: create_staging_repository
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Create GPG Key ring
        shell: bash
        run: |
          gpg --batch --pinentry-mode loopback --passphrase $passphrase --export-secret-keys -o ./secring.gpg
        env:
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Make gradlew executable
        if: matrix.platform != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Logging staging repo
        run: |
          echo $SONATYPE_REPOSITORY_ID
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository_id }}
      - id: decode
        name: Decode Base64
        shell: bash
        run: |
          repository_id=`echo -n ${{needs.create_staging_repository.outputs.repository_id}} | base64 --decode`
          echo "repository_id=$repository_id" >> $GITHUB_OUTPUT
      - name: Publish package
        shell: bash
        run: |
          ./gradlew publish -Pgradle.publish.key=$gradle_publish_key -Pgradle.publish.secret=$gradle_publish_secret -Psigning.keyId=$signing_keyId -Psigning.password=$signing_password -Psigning.secretKeyRingFile=./secring.gpg
        env:
          repoPassword: ${{ secrets.OSSRH_PASSWORD }}
          repoUsername: ${{ vars.OSSRH_USERNAME }}
          gradle_publish_key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle_publish_secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          signing_keyId: ${{ secrets.SIGNING_KEY_ID }}
          signing_password: ${{ secrets.SIGNING_PASSWORD }}
          SONATYPE_REPOSITORY_ID: ${{ steps.decode.outputs.repository_id }}
